gbook_homepage:
    pattern:  /{page}
    defaults: { _controller: EventBundle:Event:index, page: 1 }

gbook_show:
    pattern: /show/{id}
    defaults: { _controller: EventBundle:Event:show }

gbook_delete:
    pattern: /delete/{id}
    defaults: { _controller: EventBundle:Event:delete }